In [5]:
import pandas as pd

In [6]:
train_file_path = "D:\Data Science\MachineLearning\Project\MachineLearningProject1\\artifact\\data_ingestion\\2024-03-24-15-30-21\\ingested_data\\train\\train_data_housing.csv"
test_file_path =  "D:\Data Science\MachineLearning\Project\MachineLearningProject1\\artifact\\data_ingestion\\2024-03-24-15-30-21\\ingested_data\\test\\test_data_housing.csv"

In [7]:
train_data = pd.read_csv(train_file_path)
test_data = pd.read_csv(test_file_path)
target_column ='median_house_value'

In [8]:
train_data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   
1    -117.23     33.09                 7.0       5320.0           855.0   
2    -119.04     35.37                44.0       1618.0           310.0   
3    -117.13     32.75                24.0       1877.0           519.0   
4    -118.70     34.28                27.0       3536.0           646.0   

   population  households  median_income  median_house_value ocean_proximity  
0      2237.0       706.0         2.1736             72100.0          INLAND  
1      2015.0       768.0         6.3373            279600.0      NEAR OCEAN  
2       667.0       300.0         2.8750             82700.0          INLAND  
3       898.0       483.0         2.2264            112500.0      NEAR OCEAN  
4      1837.0       580.0         4.4964            238300.0       <1H OCEAN

In [9]:
train_data.shape

(16512, 10)

In [10]:
train_data[[target_column]]

median_house_value
0                 72100.0
1                279600.0
2                 82700.0
3                112500.0
4                238300.0
...                   ...
16507            268500.0
16508             90400.0
16509            140400.0
16510            258100.0
16511             62700.0

[16512 rows x 1 columns]

In [11]:
X ,y = train_data.drop(columns=[target_column]) ,train_data[[target_column]]
 

In [12]:
X.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        158
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64

In [13]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16512 entries, 0 to 16511
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           16512 non-null  float64
 1   latitude            16512 non-null  float64
 2   housing_median_age  16512 non-null  float64
 3   total_rooms         16512 non-null  float64
 4   total_bedrooms      16354 non-null  float64
 5   population          16512 non-null  float64
 6   households          16512 non-null  float64
 7   median_income       16512 non-null  float64
 8   ocean_proximity     16512 non-null  object 
dtypes: float64(8), object(1)
memory usage: 1.1+ MB


In [14]:
from sklearn.impute import SimpleImputer

In [15]:
numerical_column = X.select_dtypes(exclude='object')
categorical_column = X.select_dtypes(include="object")
categorical_column

ocean_proximity
0              INLAND
1          NEAR OCEAN
2              INLAND
3          NEAR OCEAN
4           <1H OCEAN
...               ...
16507       <1H OCEAN
16508          INLAND
16509       <1H OCEAN
16510       <1H OCEAN
16511          INLAND

[16512 rows x 1 columns]

In [16]:
impute =SimpleImputer(
    strategy='median'
)

In [17]:
impute.fit_transform(numerical_column)

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]])

In [18]:
df = impute.transform(numerical_column)

In [19]:
impute.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype=object)

In [20]:
#This value are stored inside imputer and we will use them to replace missing value
#if you got new data and that data have missing value
impute.statistics_ 


array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [21]:
impute.n_features_in_

8

In [22]:
#Applying those value on new data
# impute.transform(new_df)

In [23]:
categorical_column.value_counts()

ocean_proximity
<1H OCEAN          7277
INLAND             5262
NEAR OCEAN         2124
NEAR BAY           1847
ISLAND                2
Name: count, dtype: int64

In [24]:
cat_impute =SimpleImputer(strategy='most_frequent')


In [25]:
cat_impute.fit_transform(categorical_column)

array([['INLAND'],
       ['NEAR OCEAN'],
       ['INLAND'],
       ...,
       ['<1H OCEAN'],
       ['<1H OCEAN'],
       ['INLAND']], dtype=object)

In [26]:
cat_impute.feature_names_in_

array(['ocean_proximity'], dtype=object)

In [27]:
cat_impute.statistics_

array(['<1H OCEAN'], dtype=object)

In [28]:
type(impute)

sklearn.impute._base.SimpleImputer

In [29]:
cat_impute.n_features_in_

1

In [30]:
import numpy as np

In [31]:
np.median(train_data[['longitude']])

-118.51

In [32]:
numerical_column.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        158
population              0
households              0
median_income           0
dtype: int64

In [33]:
class FeatureGenerator():

    def __init__(self,strategy='mean'):
        self.strategy = strategy

    def fit(self,x):
        self.column = x.columns
        self.statistic_ = []
        for column in self.column :
            self.statistic_.append(x[column].mean())

        return self.statistic_

    def transform(self,x):
        for idx ,column in enumerate(x.columns):
            x[column] = x[column].fillna(self.statistic_[idx])
        return x

    def fit_transform(self,x,y):
        pass 

In [34]:
feature = FeatureGenerator()
feature.fit(x = numerical_column)
feature.transform(x=numerical_column).isna().sum()


longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
dtype: int64

In [35]:
impute.statistics_

array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [36]:
list1 = [1,2,3,4]
list2 =[2,4,6,8]

In [37]:
for idx,num in enumerate(list1):
    for i in list2:
        list1[idx] == i
    print(i)
print(list1)

8
8
8
8
[1, 2, 3, 4]


In [38]:
for idx,column in enumerate(numerical_column.columns):
    print(idx,column)

0 longitude
1 latitude
2 housing_median_age
3 total_rooms
4 total_bedrooms
5 population
6 households
7 median_income


In [39]:
from sklearn.base import BaseEstimator,TransformerMixin
from Housing.src.exception import HousingException
import os,sys

ModuleNotFoundError: No module named 'Housing.src'

In [ ]:
COLUMN_TOTAL_ROOMS = 'total_rooms' 
COLUMN_POPULATION = 'population'
COLUMN_TOTAL_BEDROOMS = 'total_bedrooms'
COLUMN_HOUSEHOLDS = 'households' 


class FeatureGenerator(BaseEstimator ,TransformerMixin):
    def __init__(self ,add_bedroom_per_romm =True ,
                 total_room_ix = 3,
                 population_ix = 5 ,
                 households_ix = 6 ,
                 total_bedroom_ix = 4 ,
                 columns =None):
        """
        total_room_ix,population_ix ,households_ix ,total_bedroom_ix are id of these column inside dataset
        """ 

        try:
            
            self.columns = columns 
            if self.columns is not None:
                total_room_ix =self.columns.index(COLUMN_TOTAL_ROOMS)
                population_ix = self.columns.index(COLUMN_POPULATION)
                total_bedroom_ix = self.columns.index(COLUMN_TOTAL_BEDROOMS)
                households_ix = self.columns.index(COLUMN_HOUSEHOLDS)
            
            self.add_bedroom_per_romm = add_bedroom_per_romm  
            self.total_room_ix = total_room_ix 
            self.population_ix =population_ix 
            self.households_ix =households_ix 
            self.total_bedroom_ix = total_bedroom_ix

        except Exception as e:
            raise HousingException(e,sys) from e
        
    def fit(self ,X,y=None):
        return self  
    


    def transform(self ,X ,y=None):
        try:
            room_per_households = X[: ,self.total_room_ix] / X[: ,self.total_bedroom_ix]
            population_per_households = X[: ,self.population_ix] / X[: ,self.households_ix]
            bedroom_per_room = X[: ,self.total_bedroom_ix]/X[: ,self.total_room_ix]
            if self.add_bedroom_per_romm:
                generated_feature = np.c_[
                    X ,room_per_households , population_per_households,bedroom_per_room
                ]
            else:
                generated_feature = np.c_[X,room_per_households ,population_per_households]
            
            return generated_feature
        
        except Exception as e:
            raise HousingException(e,sys) from e
        


In [ ]:
FeatureGenerator().fit_transform(X=X)

NameError: name 'HousingException' is not defined

In [ ]:
from sklearn.pipeline import Pipeline 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler 
from sklearn.preprocessing import OneHotEncoder

In [ ]:
num_pipeline = Pipeline(
    steps=[
        ('impute' ,SimpleImputer(strategy='median')) ,
        ('feature_generator' ,FeatureGenerator()) ,
        ('scalar' ,StandardScaler())
    ]
)
cat_pipeline = Pipeline(
    steps=[
        ('impute' ,SimpleImputer(strategy='most_frequent')) ,
        ('encode' ,OneHotEncoder()) ,
        ('scalar' ,StandardScaler())
    ]
)




In [ ]:
num_column = X.select_dtypes(exclude= 'object').columns
cat_column = X.select_dtypes(include= 'object').columns

In [ ]:
preprocessor = ColumnTransformer([
    ('num_pipeline' , num_pipeline ,num_column) ,
    ('cat_pipeline' ,cat_pipeline ,cat_column)
])

In [ ]:
preprocessor.fit_transform(X)

ValueError: Cannot center sparse matrices: pass `with_mean=False` instead. See docstring for motivation and alternatives.

In [ ]:
class DataTransform():
    def __init__(self ):
        try:
            pass 

        except Exception as e:
            raise HousingException(e,sys) from e
    def get_data_transformer_obj(self):
        try:
            pass  
        except Exception as e:
            raise HousingException(e,sys) from e  
        
         